package org.example.clientbank.dao;

import org.example.clientbank.model.Account;

import java.util.*;

/**
 * Legacy in-memory DAO kept only for compatibility with the homework package structure.
 * ID generation was removed from DAO; real IDs are generated by the database through JPA/Hibernate.
 */
public class AccountDao implements Dao<Account> {
    private final Map<Long, Account> accountMap = new HashMap<>();

    @Override
    public Account save(Account account) {
        accountMap.put(account.getId(), account);
        return account;
    }

    @Override
    public boolean delete(Account account) {
        return accountMap.remove(account.getId()) != null;
    }

    @Override
    public void deleteAll(List<Account> accounts) {
        accounts.forEach(this::delete);
    }

    @Override
    public void saveAll(List<Account> accounts) {
        accounts.forEach(this::save);
    }

    @Override
    public List<Account> findAll() {
        return new ArrayList<>(accountMap.values());
    }

    @Override
    public boolean deleteById(long id) {
        return accountMap.remove(id) != null;
    }

    @Override
    public Account getOne(long id) {
        return accountMap.get(id);
    }
}
