package org.example.clientbank.dao;

import org.example.clientbank.model.Customer;

import java.util.*;

/**
 * Legacy in-memory DAO kept only for compatibility with the homework package structure.
 * ID generation was removed from DAO; real IDs are generated by the database through JPA/Hibernate.
 */
public class CustomerDao implements Dao<Customer> {
    private final Map<Long, Customer> customerMap = new HashMap<>();

    @Override
    public Customer save(Customer customer) {
        customerMap.put(customer.getId(), customer);
        return customer;
    }

    @Override
    public boolean delete(Customer customer) {
        return customerMap.remove(customer.getId()) != null;
    }

    @Override
    public void deleteAll(List<Customer> customers) {
        customers.forEach(this::delete);
    }

    @Override
    public void saveAll(List<Customer> customers) {
        customers.forEach(this::save);
    }

    @Override
    public List<Customer> findAll() {
        return new ArrayList<>(customerMap.values());
    }

    @Override
    public boolean deleteById(long id) {
        return customerMap.remove(id) != null;
    }

    @Override
    public Customer getOne(long id) {
        return customerMap.get(id);
    }
}
